### PR TITLE
Structure the basic layout

### PR DESCRIPTION
**Pull request by ianks**
This dir structure uses a structure in which the folder structures relate to
the structure of the HTML file. Each folder represents an HTML class in the
DOM, making it easy to grok, and separate concerns wrt application design.

The dir structure looks like so. All files related to a component belong in one
folder:

```
app/components/
├── data-viewer
│   └── data-viewer.jade
├── footer
│   ├── footer.jade
│   └── footer.scss
├── header
│   ├── Header.jsx
│   ├── header.jade
│   ├── header.js
│   └── header.scss
├── template-viewer
│   └── template-viewer.jade
└── visualizer
    └── visualizer.jade
```

### CODE REVIEW

**Comment by develra** [comment]
:+1:

**Comment by ianks** [comment]
ping @wannabeCitizen, Peep this PR. There are some concepts about the structure of the app that are important. We might want to document it as well.

**Comment by wannabeCitizen** [comment]
Just got this, but am going to be working on my talk and out with some
friends for BBQ tonight.  Once I'm done doing my shit tomorrow I'll go
through this code.  (or if I get my talk done early enough tonight!)

**Comment by ianks** [comment]
Cool, we added some docs for you to read as well.

**Comment by develra** [comment]
Yo - Travis is complaining about 

"npm install && bower install" - my guess would be the operator? 

##

**Comment by ianks** [comment]
I don't think it's the operator, travis just runs BASH commands.

```
npm ERR! EEXIST, open '/home/travis/.npm/158b02ac-s-npm-minimist-1-1-0-package-tgz.lock'
File exists: /home/travis/.npm/158b02ac-s-npm-minimist-1-1-0-package-tgz.lock
Move it away, and try again. 
```

I'll take a look into it.

**Comment by ianks** [comment]
It was an NPM thing. The fix:

`npm install -g npm@next`

**Comment by ianks** [comment]
Added the ability for es6 style imports in our JS. This will allow use to keep our component structure separate from the logic of actually implementing the controller. As a side note, it helps with not polluting the global namespace to hell.

re: building components -- After some deep architecture thought and coding @develra, @peymanmortazavi and I came up with this basic (parsimonious) pattern for creating components. The document below is important to grok as it gives some info on how to build components for the main site. Note, this doesn't fully apply to the individual visualization, just the main app. Although the visualizations will follow a similar pattern. :arrow_down::arrow_down::arrow_down:

https://github.com/sikuli/viz/blob/organizational-struct/doc/component-structure.md

**Comment by develra** [comment]
Heya - I am planning on working on some component today; We good to pull?

**Comment by wannabeCitizen** [comment]
I'll trust your opinions. I get home tonight but haven't had any time to review code yet. I'm going to definitely read through the big commit from weds when home.

-Mike

**Comment by ianks** [comment]
@develra 

Merged.

**Pull request merged**
