### PR TITLE
Optimize js compilation, include React, add Travis.ci

### PR DESCRIPTION
**Pull request by ianks**
This PR allows us to now use es6 Javascript in our code. It also adds better style linting, and adds continuous integration builds using Travis.ci

### CODE REVIEW

**Comment by ianks** [comment]
@wannabeCitizen or someone with write privs, can you activate Travis for this repo?

**Comment by develra** [comment]
:+1: - with the email removal

**Comment by ianks** [comment]
Ok, I have some more commits coming up as well.

**Comment by wannabeCitizen** [comment]
I'm good on this.  Just activated Travis on the website.

**Comment by wannabeCitizen** [comment]
Are we waiting for Peyman?

**Comment by peymanmortazavi** [comment]
:+1:  sorry for delay :(

**Comment by ianks** [comment]
@wannabeCitizen plz plz don't merge other peoples PRS in the future. I had some stuff I wanted to squash down.

EDIT: It also takes away the ability to use the PR as a work-in-progress type thing, because if someone opens a PR, it could just be merged. The best way is to let the person who opened the PR merge it (if they are allowed the have merge rights, that is).

**Comment by wannabeCitizen** [comment]
If you want to have a particular workflow you want to enforce, you should a) add it to the README and b) discuss it with everyone else to ensure it's OK.  For instance, I could easily ask that no one submit a PR until you are confident that this is what you want merged (which is how Sunlight Foundation, for example, does all of their contributions.)  But I'm not that picky so I don't care.  We do, however, need to ensure people can do merges, close issues, etc without too much thought or stress.  Especially since we're not a big organization with well-defined departments and stuff where often only 1-2 people are in charge of merging code.

Honestly, every project I work on has different "rules" of managing PRs and issues so we just have to pick what's best.  

Beyond all that, have you checked if you can merge things?  If we have to, we can just tell Tom either you guys need to be owners or we will start our own org to deal with our code since there's too much confusion over who can do what.

**Comment by ianks** [comment]
If we want to keep it so only one person can merge that I can def understand the automatic merge policy. What I see in a lot of open source projects is people will use a tag like [WIP] if they don't want it merged, etc.

My understanding was this was a collaborative project, so having people handle their own merges makes sense to me. There are many situations where we may want to rebase some things, or what if we realized we forgot something? Since the author has the most knowledge of the code, it makes sense that it be his responsibility to safely get it into master. I propose that as long as they get some :+1: from somebody, they can merge. 

I just checked, and I don't think I can merge at the moment. So it makes sense that you merged it in retrospect.

**Comment by ianks** [comment]
EDIT: Actually, looks like I _can_ merge. My b.

**Pull request merged**
