### PR TITLE
Use sass indented syntax [resolves #7]

### LINKED ISSUE #7: .tmp building method is unclear for SASS
Heya,

Mike and I were messing around with the scss - trying to get the header to render in a more reasonable way. - .tmp builds on the initial pass, but then if it exists and we delete a scss file, the main.css in temp appears to still maintain those (now deleted) styles. We were looking at the gulp SCSS builder, and couldn't quite figure out what it is specifically doing. Could you take a look at this?

Thanks

### PR DESCRIPTION
**Pull request by ianks**
This allows us to use sass instead of scss

### CODE REVIEW

**Comment by develra** [comment]
:+1:

**Comment by wannabeCitizen** [comment]
Thanks Ian!  :+1: I figured it was just a matter of changing the gulpfile, but Michael and I figured that would be better for you.  We quickly ran into this problem yesterday after you and Peyman left.

One question: can you get rid of the quotation marks around the urls?  Sass shouldn't need that, but that was the first issue that Michael and I hit yesterday when trying to switch to Sass syntax.

**Comment by ianks** [comment]
@wannabeCitizen I assume you meant on the import statements? If so that is now all fixed up, along with some merge conflicts. All should be well.

**Comment by develra** [comment]
You can probably merge - I think Peyman said he was fine with it on Slack.

**Pull request merged**
